In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import netCDF4 as nc

In [2]:
# Field Data
fname = f'/srv/scratch/z3533156/26year_BRAN2020/outer_avg_01461.nc'
dataset = nc.Dataset(fname)
lon_rho = np.transpose(dataset.variables['lon_rho'], axes=(1, 0))
lat_rho = np.transpose(dataset.variables['lat_rho'], axes=(1, 0))
mask_rho = np.transpose(dataset.variables['mask_rho'], axes=(1, 0))
h = np.transpose(dataset.variables['h'], axes=(1, 0))
# f = np.transpose(dataset.variables['f'], axes=(1, 0))
angle = dataset.variables['angle'][0, 0]
z_r = np.load('/srv/scratch/z5297792/z_r.npy')
z_r = np.transpose(z_r, (1, 2, 0))
def distance(lat1, lon1, lat2, lon2):
    EARTH_RADIUS = 6357
    lat1, lon1, lat2, lon2 = map(np.radians, [lat1, lon1, lat2, lon2])
    dlat, dlon = lat2 - lat1, lon2 - lon1
    a = np.sin(dlat/2)**2 + np.cos(lat1)*np.cos(lat2)*np.sin(dlon/2)**2
    return EARTH_RADIUS * 2 * np.arctan2(np.sqrt(a), np.sqrt(1 - a))
j_mid = lon_rho.shape[1] // 2
i_mid = lon_rho.shape[0] // 2
dx = distance(lat_rho[:-1, j_mid], lon_rho[:-1, j_mid],
              lat_rho[1:, j_mid], lon_rho[1:, j_mid])
dy = distance(lat_rho[i_mid, :-1], lon_rho[i_mid, :-1],
              lat_rho[i_mid, 1:], lon_rho[i_mid, 1:])
x_grid = np.insert(np.cumsum(dx), 0, 0)
y_grid = np.insert(np.cumsum(dy), 0, 0)
X_grid, Y_grid = np.meshgrid(x_grid, y_grid, indexing='ij')

In [4]:
df_doppio_cleaned_and_checked = pd.read_pickle('/srv/scratch/z5297792/SEACOFS_26yr_eddy_dataset/DOPPIO_SEACOFS_26yr_50m_vert_check/df_DOPPIO_SEACOFS_26yr_cleaned_and_checked.pkl')
df_doppio_cleaned_and_checked

,Day,fnumber,nxc,nyc,Cyc,xc,yc,w,Q,Omega0,Omega,Rc,psi0,R,err,Omega0_abs,fname,reaches_50m,ic,jc
0,1462,1461,830.0,1515.0,AE,829.879126,1515.297884,0.000016,"[[0.7054724746035225, -0.17299518294950286], [...",0.000007,0.000008,96.456316,-38.462785,63.384028,0.321474,0.000007,/srv/scratch/z3533156/26year_BRAN2020/outer_av...,True,245,307
1,1462,1461,358.0,1408.0,AE,357.902634,1407.794571,0.000032,"[[1.2525415454561337, -0.37318304544145586], [...",0.000015,0.000014,78.042405,-41.260426,50.068171,0.227335,0.000015,/srv/scratch/z3533156/26year_BRAN2020/outer_av...,True,136,285
2,1462,1461,928.0,1356.0,CE,928.181752,1356.070550,-0.000011,"[[0.9184334895938384, -0.6568144522261018], [-...",-0.000004,-0.000007,118.032741,47.992205,74.597458,0.194964,0.000004,/srv/scratch/z3533156/26year_BRAN2020/outer_av...,True,261,274
3,1462,1461,506.0,1354.0,CE,505.750855,1353.499933,-0.000032,"[[1.0915204469734063, -0.17483272531676586], [...",-0.000016,-0.000013,106.666574,75.106895,69.457705,0.558695,0.000016,/srv/scratch/z3533156/26year_BRAN2020/outer_av...,True,179,274
4,1462,1461,754.0,1285.0,AE,753.849693,1284.689807,0.000022,"[[1.300245004042572, -0.37537759847059776], [-...",0.000010,0.000008,103.327517,-44.066805,65.961546,0.344691,0.000010,/srv/scratch/z3533156/26year_BRAN2020/outer_av...,True,231,260
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
367189,10650,10641,349.0,158.0,AE,348.663439,158.138527,0.000033,"[[1.3863808771116255, 0.04649055064735413], [0...",0.000016,0.000012,110.552001,-72.997132,43.099927,0.363955,0.000016,/srv/scratch/z3533156/26year_BRAN2020/outer_av...,True,133,32
367190,10650,10641,973.0,126.0,CE,978.294053,127.970950,-0.000004,"[[0.6233322936879349, -0.5502050858849237], [-...",-0.000001,-0.000002,75.127332,4.241051,34.482872,5.649039,0.000001,/srv/scratch/z3533156/26year_BRAN2020/outer_av...,False,269,26
367191,10650,10641,805.0,95.0,AE,804.765913,95.382012,0.000011,"[[1.2619918374118362, 0.3980497594289241], [0....",0.000005,0.000006,60.426625,-10.779905,45.893895,0.448028,0.000005,/srv/scratch/z3533156/26year_BRAN2020/outer_av...,True,240,19
367192,10650,10641,157.0,34.0,CE,157.210669,33.449590,-0.000007,"[[0.9874338034387458, 0.628992620695803], [0.6...",-0.000003,-0.000004,141.142981,36.082072,34.764443,0.589349,0.000003,/srv/scratch/z3533156/26year_BRAN2020/outer_av...,False,57,7
367193,10650,10641,662.0,13.0,CE,662.493367,12.691756,-0.000005,"[[0.8074064067247743, 0.12727284340477454], [0...",-0.000003,-0.000001,176.570139,22.703466,31.106318,0.581744,0.000003,/srv/scratch/z3533156/26year_BRAN2020/outer_av...,False,214,3

In [5]:
df_doppio_cleaned_and_checked[df_doppio_cleaned_and_checked.reaches_50m]

,Day,fnumber,nxc,nyc,Cyc,xc,yc,w,Q,Omega0,Omega,Rc,psi0,R,err,Omega0_abs,fname,reaches_50m,ic,jc
0,1462,1461,830.0,1515.0,AE,829.879126,1515.297884,0.000016,"[[0.7054724746035225, -0.17299518294950286], [...",0.000007,0.000008,96.456316,-38.462785,63.384028,0.321474,0.000007,/srv/scratch/z3533156/26year_BRAN2020/outer_av...,True,245,307
1,1462,1461,358.0,1408.0,AE,357.902634,1407.794571,0.000032,"[[1.2525415454561337, -0.37318304544145586], [...",0.000015,0.000014,78.042405,-41.260426,50.068171,0.227335,0.000015,/srv/scratch/z3533156/26year_BRAN2020/outer_av...,True,136,285
2,1462,1461,928.0,1356.0,CE,928.181752,1356.070550,-0.000011,"[[0.9184334895938384, -0.6568144522261018], [-...",-0.000004,-0.000007,118.032741,47.992205,74.597458,0.194964,0.000004,/srv/scratch/z3533156/26year_BRAN2020/outer_av...,True,261,274
3,1462,1461,506.0,1354.0,CE,505.750855,1353.499933,-0.000032,"[[1.0915204469734063, -0.17483272531676586], [...",-0.000016,-0.000013,106.666574,75.106895,69.457705,0.558695,0.000016,/srv/scratch/z3533156/26year_BRAN2020/outer_av...,True,179,274
4,1462,1461,754.0,1285.0,AE,753.849693,1284.689807,0.000022,"[[1.300245004042572, -0.37537759847059776], [-...",0.000010,0.000008,103.327517,-44.066805,65.961546,0.344691,0.000010,/srv/scratch/z3533156/26year_BRAN2020/outer_av...,True,231,260
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
367185,10650,10641,852.0,485.0,AE,851.944525,484.893238,0.000014,"[[0.9007012006328585, 0.20548487615413524], [0...",0.000007,0.000006,122.098704,-47.886436,68.779464,0.120315,0.000007,/srv/scratch/z3533156/26year_BRAN2020/outer_av...,True,248,98
367186,10650,10641,507.0,302.0,CE,507.317516,301.765848,-0.000026,"[[1.0708738864553369, -0.01900508766730702], [...",-0.000013,-0.000009,69.621926,22.250327,39.742296,0.394517,0.000013,/srv/scratch/z3533156/26year_BRAN2020/outer_av...,True,179,61
367188,10650,10641,860.0,180.0,CE,859.994476,179.913208,-0.000008,"[[0.564056467889216, 0.17870736849564053], [0....",-0.000003,-0.000004,80.423861,12.360816,62.024070,0.086968,0.000003,/srv/scratch/z3533156/26year_BRAN2020/outer_av...,True,250,36
367189,10650,10641,349.0,158.0,AE,348.663439,158.138527,0.000033,"[[1.3863808771116255, 0.04649055064735413], [0...",0.000016,0.000012,110.552001,-72.997132,43.099927,0.363955,0.000016,/srv/scratch/z3533156/26year_BRAN2020/outer_av...,True,133,32
367191,10650,10641,805.0,95.0,AE,804.765913,95.382012,0.000011,"[[1.2619918374118362, 0.3980497594289241], [0....",0.000005,0.000006,60.426625,-10.779905,45.893895,0.448028,0.000005,/srv/scratch/z3533156/26year_BRAN2020/outer_av...,True,240,19